### ISSUE TITLE
Maintenance window API integration

### ISSUE THREAD

**Issue by onitake** [unprofession-al/bpmon#23]
When planning large infrastructure changes, it would be very helpful to create maintenance windows directly from bpmon.

One possibility would be to use monitoring APIs (like https://www.icinga.com/docs/icinga2/latest/doc/12-icinga2-api/#schedule-downtime ).

On the bpmon side, an additional command with business process name, start time and end time arguments could be added.

**Comment by sontags** [comment]
In the current master the `run` subcommand allows to provide a custom template. Consider the following template:

```
...
templates:  icinga_downtime:
    template: |-
      #!/bin/bash
      {{- $api := .Config.Checker.Connection -}}
      {{- $start := index .Parameters "start" -}}
      {{- $end := index .Parameters "end" }}

      author="{{ index .Parameters "author" }}"
      comment="{{ index .Parameters "comment" }}"
      start=$(date -d '{{$start}}' +%s)
      end=$(date -d '{{$end}}' +%s)
      data="'{ \"start_time\": $start, \"end_time\": $end, \"author\": \"$author\", \"comment\": \"$comment\", \"pretty\": true }'"
      {{ range $index, $bp := .BP }}
        {{- range $index, $kpi := .Children }}
          {{- range $index, $svc := .Children }}
      curl -s -H 'Accept: application/json' -X POST '{{$api}}/v1/actions/schedule-downtime?service={{$svc.Name}}' -d $data;
          {{- end -}}
        {{ end -}}
      {{ end -}}
    description: Prints a cURL command for each serivce to schedule a downtime via
      Icinga2 API (https://icinga.com/docs/icinga2/latest/doc/12-icinga2-api/#schedule-downtime)
    parameters:
      author: Your Name
      comment: Reason for the downtime
      end: Must match pattern (YYYY-MM-DD hh:mm:ss)
      start: Must match pattern (YYYY-MM-DD hh:mm:ss)
...
```

Using this template `bpmon` generates a bash script that calls the Icinga API and schedules a downtime. `author`, `comment`, `start` and `end` will be prompted if not provided via `--params "author=onitake,comment=Big Maintenance"`. Execute via...

```
bpmon -c conf.yaml -b bp.d run icinga_downtime | bash
```

To limit on a BP use the `--pattern/-p` option. Using this implementation all sorts of stuff can be achieved. I am not quite sure if standard `text/template` is a good match and the templating stuff needs a good amount of documentation.

Please have a look and let me know if this makes sense to you...

**Comment by sontags** [comment]
[Runners](https://bpmon.unprofession.al/docs/6_writerunners/) have now been integrated...

**Comment by onitake** [comment]
Much broader scope than anticipated.
The only downside is that with the current implementation, templates need to be carried along with the bpmon binary. But I guess it's worth the added flexibility.
